### ISSUE TITLE
Bower support

### ISSUE THREAD

**Issue by TheJaredWilcurt** [esr360/Synergy#4]
Add a bower.json and submit the package to bower.io for use as a dependency in other projects.

**Comment by esr360** [comment]
Funnily enough there was Bower support up until version 3.2 but then I removed it as I felt as a whole bower usage is dropping. The package itself probably does still exist on bower as I don't recall removing it.

I will see about re-adding it for the next release which should be shortly. Thanks for the feedback!

**Comment by TheJaredWilcurt** [comment]
lol, yeah I was of the same impression and even encouraged people to stop using it. "If everything you need is already on NPM, why download NPM, use it to download Bower, just to get what you already had on NPM."

Then I started looking into Sass Mixins for [Scout-App 2](https://github.com/TheJaredWilcurt/scout-app) and found that almost all of them were on Bower, and almost none were on NPM. So Now I'm just using solely Bower for them.

**Comment by tosfan4ever** [comment]
What the fuck is this?

**Comment by TheJaredWilcurt** [comment]
![](http://i.imgur.com/sWrYbm6.jpg)

**Comment by tosfan4ever** [comment]
Can u remove me? I DON'T REMEMBER COMMENTING

**Comment by esr360** [comment]
@tosfan4ever no can do you are in this forever now

**Comment by tosfan4ever** [comment]
Well fuck you all!

**Comment by TheJaredWilcurt** [comment]
![](https://cloud.githubusercontent.com/assets/4629794/13898842/3b7ae0ca-edb5-11e5-8c20-a965ab6f46e5.png)

**Comment by esr360** [comment]
Bower support re-added as of version 3.3

**Comment by TheJaredWilcurt** [comment]
It actually isn't on the Bower website:

* http://bower.io/search

So doing

```
dependencies: {
    "synergy": "latest"
}
```

Won't work, you have to give a specific version number (3.3.0) instead of latest because bower.exe will check their site for the latest version and fail.

**Comment by esr360** [comment]
Perhaps it took some time to register but I can see Synergy on the bower search page, and version 3.3.0 is [specified in bower.json](https://github.com/esr360/Synergy/blob/master/bower.json#L4).

**Comment by TheJaredWilcurt** [comment]
Turns out they are case sensitive, so if I search "synergy" I get 0 results, but "Synergy" returns 1.

same with the dependency

```
dependencies: {
    "Synergy": "latest"
}
```

that works
